version: '3.5'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    labels:
      nl.demeyerthom.environment: testing
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "publication-pages:1:1,publications:1:1,company-pages:1:1,companies:1:1"
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
    labels:
      nl.demeyerthom.environment: testing
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/kafka:/kafka
    depends_on:
      - zookeeper

  tor:
    image: peterdavehello/tor-socks-proxy
    labels:
      nl.demeyerthom.environment: testing
    ports:
      - 9150:9150

  arangodb:
    image: arangodb:latest
    ports:
      - 8530:8529
    volumes:
      - ./docker/arangodb:/var/lib/arangodb3
    environment:
      - ARANGO_NO_AUTH=1
    labels:
      nl.demeyerthom.environment: testing

  redis:
    image: redis
    ports:
      - 6379:6379
    labels:
      nl.demeyerthom.environment: testing
    volumes:
      - ./docker/redis:/data
