version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "publication-pages:1:1,publications:1:1,company-pages:1:1,companies:1:1"
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/kafka:/kafka
    depends_on:
      - zookeeper

  tor:
    image: peterdavehello/tor-socks-proxy:latest
    ports:
      - 9150:9150
