[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/grokify/html-strip-tags-go"

[[constraint]]
  branch = "master"
  name = "github.com/segmentio/kafka-go"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.6"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
[[constraint]]
  name = "github.com/microcosm-cc/bluemonday"
  version = "1.0.1"
