[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/vjeantet/jodaTime"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/grokify/html-strip-tags-go"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  branch = "master"
  name = "github.com/segmentio/kafka-go"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.6"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.1.0"

[[constraint]]
  branch = "v3"
  name = "gopkg.in/sohlich/elogrus.v3"

[[constraint]]
  name = "github.com/sarulabs/di"
  version = "2.1.0"

[[constraint]]
  name = "github.com/segmentio/ksuid"
  version = "1.0.2"
